[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "16.14.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
